### ISSUE TITLE
how would i make songs in the hotfix? 

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SanicBTW/FNF-PsychEngine-0.3.2-hotfix#28]
I made a version with just the page i dont really  know how to add shit there

**Comment by SanicBTW** [comment]
In order to add songs you must add them to WeekData.hx (source code) I don't think that the free play song list is working.
Once you added your song to WeekData.hx and added the required files (charts "songName.json" and music "Inst.mp3" / "Voices.mp3") wait until the project is recompiled (workflow) and move it into the page

**Comment by LEVIXDDLMAO** [comment]
Yo so it wont recompile it fails

**Comment by LEVIXDDLMAO** [comment]
it gets to script run lime haha and then fails

**Comment by SanicBTW** [comment]
Maybe I can help you through some social media or something

**Comment by LEVIXDDLMAO** [comment]
Sure heres my email Dontblock012@outlook.com

**Comment by LEVIXDDLMAO** [comment]
i could send you a screen shot of my error

**Comment by LEVIXDDLMAO** [comment]
?

**Comment by SanicBTW** [comment]
sure

**Comment by LEVIXDDLMAO** [comment]
![Screenshot 2022-04-15 3 57 28 PM](https://user-images.githubusercontent.com/92174516/163638402-230219cd-fb29-43c8-bfbf-29d9e0f1c397.png)
oh and one more thing
